### ISSUE TITLE
Support for v406510 - 12th of March

### ISSUE THREAD

**Issue by AdiBorsos** [AdiBorsos/AutoSteamworks#11]
Figure out the new memory addresses :)

**Comment by Zirconium2159** [comment]
Is it solved?

**Comment by ssapgosu12** [comment]
is it solved??

**Comment by Jaessun** [comment]
@AdiBorsos Found the new memory address for the steamworks combo. I didn't find the new address for the save data though, and I don't really know how to approach finding that.

In the meantime I forked the repo and patched it while commenting out usage of save data, which basically means it does the 100% accuracy combinations again, but doesn't detect when you're out of fuel anymore.

Here's the link to my fork if you wanna check it out: https://github.com/Jaessun/AutoSteamworks/

**Comment by AdiBorsos** [comment]
Wow really nice, how did you find it ? Wanna make a pull request in repo to add it yourself or should i ?

**Comment by Jaessun** [comment]
Thanks! Found it with Cheat Engine by scanning for the address and then scanning for pointers that point to that address until I find the correct pointer. Sure I can make a pull request!

**Comment by ssapgosu12** [comment]
woo! thats nice.

**Comment by AdiBorsos** [comment]
I will make a minor release for this to give people the chance to use it even without the cool retry and stop mechanisms while i look into the other pointer. Marcus' table also has some aob scanning for new pointers and it works for most addresses but not for the save game editor yet. Check his table, maybe you can figure it out.

**Comment by AdiBorsos** [comment]
Done
