### ISSUE TITLE
Support for v13.0.0 (build 4854341)

### ISSUE THREAD

**Issue by tolly765** [AdiBorsos/AutoSteamworks#15]
New build for MHW was pushed out for Raging Brachy and Furious Rajang. I guess it's time to find new memory addresses?

**Comment by Zirconium2159** [comment]
To be exact,it is now 13.0.1(410013) for the steam version.

**Comment by kaiwang13** [comment]
Suggest to put Settings.SupportedGameVersion into config

**Comment by AdiBorsos** [comment]
It wouldn't be a good idea to put it in config as you want to updated it only with compiled code. This way people won't be tempted to change it. Pointers change anyway after an update and the app won't work.

Update done :). See the new v9.

**Comment by kaiwang13** [comment]
Thank you very much!

**Comment by tolly765** [comment]
My bad, the full bloom fest pushed shortly after I opened the issue. I probably should have waited for that hotfix before posting.

Regardless, thank you for the update 👍
