### ISSUE TITLE
Title update v15.01.00 (5545444)

### ISSUE THREAD

**Issue by tolly765** [AdiBorsos/AutoSteamworks#21]
Monster Hunter: WORLD has received the Fatalis update, and the version has changed. This should be the last "major" update that the game receives as World is now on EoL. Any chance of an update?

**Comment by AdiBorsos** [comment]
Hey, as i also mentioned on nexus. I will be working on an update

**Comment by 1025431504** [comment]
I can't play steam engines without magic

**Comment by AdiBorsos** [comment]
Update complete
