### ISSUE TITLE
[Solved by https://github.com/Geobryn ]100% success

### ISSUE THREAD

**Issue by Geobryn** [AdiBorsos/AutoSteamworks#3]
for some reason the 2 0 1 sequence is switched with the 1 2 0 one
so right after `var orderBytes = BitConverter.GetBytes(actualSequence);` in `ExtractCorrectSequence` method
i put this abomination and i get 100% success

```
if (orderBytes[0] == 2 && orderBytes[1] == 0 && orderBytes[2] == 1)
{
    orderBytes[0] = 1;
    orderBytes[1] = 2;
    orderBytes[2] = 0;
}
else if (orderBytes[0] == 1 && orderBytes[1] == 2 && orderBytes[2] == 0)
{
    orderBytes[0] = 2;
    orderBytes[1] = 0;
    orderBytes[2] = 1;
}
```

**Comment by AdiBorsos** [comment]
Wow, really? So that is why it failed sometimes no matter how good my sync was. How did you figure this out?

**Comment by Geobryn** [comment]
well... was watching steamworks while having dinner and spotted the pattern :P
then just tried crudely patch it in for lols and well...

**Comment by AdiBorsos** [comment]
Yea, i just tried it ... amazing man .. Great job. I just pushed the code ..
