### ISSUE TITLE
End Cutscene skip

### ISSUE THREAD

**Issue by Geobryn** [AdiBorsos/AutoSteamworks#4]
in System > Options > Controls > Keyboard Settings > Menu Control
almost at the bottom there is keybind "Use or Register Loadout / Cancel Animation"
default is "X"

compared to "Esc", which when spammed will leave steamworks, can be spammed without any issues
i tried to put it into this loop right after `try` and it works great, even with all the delays at 50 millis

let the ppl set their bind in app.config and place it at a more correct place would be better approach...
```
while (currentState != (int)ButtonPressingState.BeginningOfSequence)
{
    Thread.Sleep(50);

    try
    {
        PressKey(sim, VirtualKeyCode.VK_X);
```

**Comment by AdiBorsos** [comment]
you should create pull requests so you get added to contributors> please do that so you get the right credit.
